services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=solardb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=solaruser'
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U solaruser -d solardb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solar_backend
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/solardb'
      - 'SPRING_DATASOURCE_USERNAME=solaruser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: solar_frontend
    ports:
      - '3000:3000'
    environment:
      - 'NODE_ENV=production'
    depends_on:
      - backend

volumes:
  postgres-data:
